/**
 * Builds the machine-readable map of the vault: `llms.txt` and `INDEX.md`.
 *
 * The point is that somebody — or something — can point a model at this repository and get a
 * correct answer with a citation, rather than a plausible one. So every concept in the index
 * carries the documentation pages it was written from, and the date each was last checked.
 *
 * Generated, never hand-edited: a map that drifts from the territory is worse than no map.
 * Runs in CI, so a pull request that adds a concept updates the index in the same commit.
 *
 * Usage: node scripts/index.ts [--check]
 */
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

const HERE = path.resolve(import.meta.dirname ?? path.dirname(new URL(import.meta.url).pathname), '..');
const ROOT = path.join(HERE, 'content');
const SITE = 'https://lakenaut.dev';
const check = process.argv.includes('--check');

const walk = (dir: string, ext = '.md'): string[] =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
        const full = path.join(dir, e.name);
        return e.isDirectory() ? walk(full, ext) : e.name.endsWith(ext) ? [full] : [];
      })
    : [];

interface Doc {
  data: Record<string, any>;
  file: string;
}
const read = (dir: string, ext = '.md'): Doc[] => walk(dir, ext).map((file) => ({ data: matter(fs.readFileSync(file, 'utf8')).data, file }));

const concepts = read(path.join(ROOT, 'concepts'));
const areas = read(path.join(ROOT, 'areas'));
const paths = read(path.join(ROOT, 'paths'));
const roadmaps = read(path.join(ROOT, 'roadmaps'));

const areaById = new Map(areas.map((a) => [a.data.id, a.data]));
const GROUPS: [string, string][] = [
  ['foundations', 'Foundations'],
  ['main', 'Workspace'],
  ['sql', 'SQL & Analytics'],
  ['data-engineering', 'Data Engineering'],
  ['ai-ml', 'AI & Machine Learning'],
];

const published = concepts.filter((c) => c.data.status === 'published');
const sourcesOf = (d: Record<string, any>): { url: string; checked?: string }[] => (Array.isArray(d.sources) ? d.sources : []);
const iso = (v: unknown) => (v instanceof Date ? v.toISOString().slice(0, 10) : String(v ?? '').slice(0, 10));

// ---------- llms.txt ----------
// The convention: a short description, then links, so a model can find its way in one fetch.
const llms = [
  '# Lakenaut',
  '',
  '> Databricks explained one concept per file. Every page is written from the official',
  '> documentation and cites the pages it was written from, with the date each was checked.',
  '> Product names are used as nomenclature; this project is not affiliated with Databricks.',
  '',
  `This repository is the source. The rendered site is ${SITE}.`,
  '',
  `- ${published.length} concepts, each a markdown file with frontmatter (id, area, level, summary, sources, updated, maturity)`,
  `- ${paths.length} learning paths, ${roadmaps.length} certification roadmaps anchored to published exam guides`,
  '- Renames, previews and end-of-support dates as structured YAML, not prose',
  '',
  '## How to use it',
  '',
  '- [INDEX.md](INDEX.md): every concept, with its summary and the documentation it cites.',
  '- [CLAUDE.md](CLAUDE.md): the conventions — frontmatter shape, folder rules, what may and may not be copied.',
  `- [${SITE}/concepts.json](${SITE}/concepts.json): the same index as JSON, always current.`,
  `- [${SITE}/taxonomy.json](${SITE}/taxonomy.json): areas, paths, certifications and topics, as ids.`,
  `- [${SITE}/llms.txt](${SITE}/llms.txt): the site's own map.`,
  '',
  '## Rules for anyone quoting this',
  '',
  '- The prose is CC BY-NC-SA 4.0; the code is MIT. See LICENSE and LICENSE-CODE.',
  '- Cite the concept and its own sources, not this file. A concept names the pages it was',
  '  written from; those pages, not this repository, are the authority on the product.',
  '- Check `updated` and `maturity` before repeating anything: the platform changes weekly, and',
  '  a concept marked `beta` or `public-preview` describes something that may not exist next month.',
  '',
  '## Sections',
  '',
  ...GROUPS.map(([g, label]) => {
    const n = published.filter((c) => areaById.get(c.data.area)?.sidebar_group === g).length;
    return `- ${label}: ${n} concepts`;
  }),
  '',
].join('\n');

// ---------- INDEX.md ----------
const lines: string[] = [
  '<!-- Generated by scripts/index.ts. Do not edit by hand: run `npm run index`. -->',
  '',
  '# The whole vault, in one page',
  '',
  `${published.length} published concepts, grouped the way the site groups them. Each one links to its`,
  'page on the site, to the file here, and to the documentation it was written from.',
  '',
  '| | |',
  '| --- | --- |',
  `| Concepts | ${published.length} published, ${concepts.length - published.length} in progress |`,
  `| Learning paths | ${paths.length} |`,
  `| Certifications | ${roadmaps.length} |`,
  `| Areas | ${areas.length} |`,
  '',
];

for (const [group, label] of GROUPS) {
  const inGroup = areas.filter((a) => a.data.sidebar_group === group).sort((a, b) => (a.data.order ?? 99) - (b.data.order ?? 99));
  if (!inGroup.length) continue;
  lines.push(`## ${label}`, '');
  for (const area of inGroup) {
    const list = published.filter((c) => c.data.area === area.data.id).sort((a, b) => String(a.data.title).localeCompare(String(b.data.title)));
    if (!list.length) continue;
    lines.push(`### ${area.data.label ?? area.data.title}`, '');
    for (const c of list) {
      const d = c.data;
      const src = sourcesOf(d)
        .map((s) => `[docs](${s.url})${s.checked ? ` <sub>${iso(s.checked)}</sub>` : ''}`)
        .join(' · ');
      const badge = d.maturity && d.maturity !== 'ga' ? ` \`${d.maturity}\`` : '';
      lines.push(
        `- **[${d.title}](${SITE}/concepts/${d.id}/)**${badge} — ${d.summary}  `,
        `  <sub>\`${d.id}\` · ${d.level ?? 'beginner'} · updated ${iso(d.updated)} · [source](${path.relative(HERE, c.file)})${src ? ` · ${src}` : ''}</sub>`,
      );
    }
    lines.push('');
  }
}

lines.push(
  '## Learning paths',
  '',
  ...paths
    .sort((a, b) => (a.data.order ?? 99) - (b.data.order ?? 99))
    .map((p) => `- **[${p.data.title}](${SITE}/paths/${p.data.id}/)** — ${p.data.summary} <sub>${(p.data.stages ?? []).length} stages</sub>`),
  '',
  '## Certifications',
  '',
  ...roadmaps.map(
    (r) => `- **[${r.data.title}](${SITE}/roadmaps/${r.data.id}/)** — exam guide ${r.data.exam_guide_version} · [official guide](${r.data.exam_guide_url})`,
  ),
  '',
);

const out: [string, string][] = [
  [path.join(HERE, 'llms.txt'), llms],
  [path.join(HERE, 'INDEX.md'), lines.join('\n')],
];

let stale = false;
for (const [file, content] of out) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (current === content) continue;
  stale = true;
  if (!check) fs.writeFileSync(file, content);
}

if (check && stale) {
  console.error('INDEX.md or llms.txt is out of date. Run `npm run index` and commit the result.');
  process.exit(1);
}
console.log(check ? 'index is current' : `wrote llms.txt and INDEX.md — ${published.length} concepts`);
